
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MASMAS = 25;
  public static final int MENOSMENOS = 26;
  public static final int MULT = 11;
  public static final int CHAR = 36;
  public static final int ENTERO = 38;
  public static final int REPEAT = 51;
  public static final int DIVIGUAL = 33;
  public static final int INT = 34;
  public static final int IMPLICA = 22;
  public static final int FOR = 50;
  public static final int CP = 5;
  public static final int MULTIGUAL = 32;
  public static final int NOT = 21;
  public static final int MENORIGUAL = 18;
  public static final int AND = 19;
  public static final int IGUAL = 13;
  public static final int CARACTER = 40;
  public static final int MASIGUAL = 30;
  public static final int DESPDERECHA = 28;
  public static final int OR = 20;
  public static final int DIV = 12;
  public static final int IF = 43;
  public static final int MAYORIGUAL = 17;
  public static final int BOOLEAN = 35;
  public static final int DIST = 14;
  public static final int EOF = 0;
  public static final int ASIG = 7;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int JUST = 53;
  public static final int MODULO = 29;
  public static final int MENOS = 10;
  public static final int MENOR = 16;
  public static final int IDENT = 42;
  public static final int MENOSUNARIO = 24;
  public static final int CLL = 3;
  public static final int ELVIS = 47;
  public static final int REAL = 41;
  public static final int MAYOR = 15;
  public static final int TIMES = 52;
  public static final int INTERROGANTE = 45;
  public static final int ELSE = 44;
  public static final int WHILE = 49;
  public static final int FLOAT = 37;
  public static final int MENOSIGUAL = 31;
  public static final int BOOLEANO = 39;
  public static final int DOBLEIMPLICA = 23;
  public static final int ALL = 2;
  public static final int DESPIZQUIERDA = 27;
  public static final int AP = 4;
  public static final int DP = 46;
  public static final int PRINT = 54;
  public static final int DO = 48;
  public static final int PYC = 6;
  public static final int MAS = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ALL",
  "CLL",
  "AP",
  "CP",
  "PYC",
  "ASIG",
  "COMA",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "IGUAL",
  "DIST",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "AND",
  "OR",
  "NOT",
  "IMPLICA",
  "DOBLEIMPLICA",
  "MENOSUNARIO",
  "MASMAS",
  "MENOSMENOS",
  "DESPIZQUIERDA",
  "DESPDERECHA",
  "MODULO",
  "MASIGUAL",
  "MENOSIGUAL",
  "MULTIGUAL",
  "DIVIGUAL",
  "INT",
  "BOOLEAN",
  "CHAR",
  "FLOAT",
  "ENTERO",
  "BOOLEANO",
  "CARACTER",
  "REAL",
  "IDENT",
  "IF",
  "ELSE",
  "INTERROGANTE",
  "DP",
  "ELVIS",
  "DO",
  "WHILE",
  "FOR",
  "REPEAT",
  "TIMES",
  "JUST",
  "PRINT"
  };
}

